### PR TITLE
update hawq stop options

### PR DESCRIPTION
**Pull request by daixiang0**
update hawq help info

Signed-off-by: daixiang0 <764524258@qq.com>

### CODE REVIEW

**Comment by daixiang0** [comment]
@jiny2 @huor Hi, the failure seems jenkins env issue. Could input anything?

**Comment by huor** [comment]
@daixiang0 the apache license header information is missing in below files:
```
[WARNING] Files with unapproved licenses:
  contrib/orc/cwrapper/format/Makefile
  contrib/orc/cwrapper/Makefile
```

**Comment by daixiang0** [comment]
@huor thanks for your input. I am new to PR and just fork this project, seems that it need a license right? What can i do to fix it?

**Comment by huor** [comment]
You can add content of line 1 ~ 17 in contrib/orc/Makefile in contrib/orc/cwrapper/format/Makefile and contrib/orc/cwrapper/Makefile

**Comment by daixiang0** [comment]
Ld still failed in build.

**Comment by daixiang0** [comment]
@huor hi, any input?

**Comment by daixiang0** [comment]
any update?

**Comment by daixiang0** [comment]
@huor any update?

**Comment by daixiang0** [comment]
@huor any update?

**Comment by daixiang0** [comment]
@jianlirong hi, i found that hawq cli help is too old and i want to sync help info, which is all i do in this PR.

**Comment by jianlirong** [comment]
OK. I see.

Lirong


Xiang Dai <notifications@github.com> 于2019年1月14日周一 上午9:39写道：

**Comment by daixiang0** [comment]
@jianlirong any update?

**Comment by jianlirong** [comment]
@huor  and @jiny2 , would you please have a look at this PR? It LGTM. If everything is ok, please merge this PR into the master branch. It seems there is some problem with my Apache account, so that I couldn't perform the merge operation. Many thanks in advance.

Lirong

**Comment by khaiphan9x** [comment]
Asia/Saigon to Asia/Ho_Chi_Minh

**Comment by daixiang0** [comment]
@huor  @jiny2 any input?

**Comment by huor** [comment]
I am working on it. Will update you guys when it is done.

**Comment by huor** [comment]
Looks good to me +1

**Comment by daixiang0** [comment]
@huor fix conflict.

**Comment by huor** [comment]
@daixiang0, would you please shed some light on "fix conflict" before I merge your commit to master? Thanks.

**Comment by daixiang0** [comment]
Just github show some conflicts then i fix them.

**Comment by huor** [comment]
@daixiang0, I see. Just went through your commit in this PR, seems that I need to only merge 2c95dce2191107eeaac854e48bee025ffe052ece to master, while 3076c5fccd44585557e0b3fc245dce3066dec4c0 and fe23d9722ad0c4eda2f1707b8aee542d7461af95 have been addressed in master. If this is true, I will merge it right away.

**Comment by daixiang0** [comment]
yes, that is true.

**Comment by huor** [comment]
Merged to master.

**Comment by huor** [comment]
You can close this PR.

**Comment by daixiang0** [comment]
@huor thanks.

**Pull request closed without merging**
