### PR TITLE
aarch64 port changes

### PR DESCRIPTION
**Pull request by RamaMalladiAWS**
These are code changes for building `apache/hawq` on `aarch64` architecture processors.

### CODE REVIEW

**Review by RamaMalladiAWS — COMMENTED** [review]
Please review and approve merge to build `apache/hawq` on `aarch64` architecture processor.

**Review by RamaMalladiAWS — COMMENTED** [review]
Can this PR be reviewed and approved for merge please? Thanks. This is required for building libhdfs3 for aarch64.

**Comment by ztao1987** [comment]
please squash your commits.

**Comment by RamaMalladiAWS** [comment]
> please squash your commits.

Done. Thank you.

**Comment by ztao1987** [comment]
Also you need to file a HAWQ issue, and rename the commit to HAWQ-XXXX. aarch64 port changes

**Comment by RamaMalladiAWS** [comment]
> Also you need to file a HAWQ issue, and rename the commit to HAWQ-XXXX. aarch64 port changes

Hi @ztao1987, thank you. I sent a note to private@hawq.apache.org asking for a JIRA account to be created. Post getting that, I will file a HAWQ issue and modify the commit message.

**Comment by ztao1987** [comment]
I have filed this: https://issues.apache.org/jira/browse/HAWQ-1853.

**Comment by RamaMalladiAWS** [comment]
> I have filed this: https://issues.apache.org/jira/browse/HAWQ-1853.

Thank you very much. I modified the commit message to "HAWQ-1853. aarch64 port changes".

**Comment by ztao1987** [comment]
ok, it looks good to me. Will merge it.

**Comment by RamaMalladiAWS** [comment]
> ok, it looks good to me. Will merge it.

Thank you much.

**Pull request merged**
